ALTER TABLE users 
ALTER COLUMN full_name SET NOT NULL, ---É ASSIM QUE DEFINIMOS UMA CONSTRAINT EM 1 COLUMN, EM 1 TABLE, POR MEIO DE 'ALTER TABLE' (aí não precisamos RECRIAR A TABLE)...
ALTER COLUMN current_status SET NOT NULL
;   