
-- SELECT * FROM customers; -- ISSO PEGA TODOS OS CAMPOS DE CADA 'customer', nessa table de CUSTOMERS...

SELECT email FROM customers;  -- ISSO PEGA OS VALUES DE TODOS CAMPOS 'email', na table de 'CUSTOMERS'...